AWSTemplateFormatVersion: '2010-09-09'

Resources:

  ResumeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub resume-site-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  ResumeBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ResumeBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${ResumeBucket.Arn}/*"

  DeploymentTracking:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DeploymentTracking
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: commit_sha
          AttributeType: S
      KeySchema:
        - AttributeName: commit_sha
          KeyType: HASH

  ResumeAnalytics:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ResumeAnalytics
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: commit_sha
          AttributeType: S
      KeySchema:
        - AttributeName: commit_sha
          KeyType: HASH

Outputs:
  BucketName:
    Value: !Ref ResumeBucket
